// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package obs

import (
	"github.com/cqroot/minstor/internal/config"
	"github.com/cqroot/minstor/internal/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitObs() (*Obs, error) {
	obsConfig, err := config.NewObsConfig()
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.New(obsConfig)
	obs := New(obsConfig, zerologLogger)
	return obs, nil
}

// wire.go:

var ConfigSet = wire.NewSet(config.NewObsConfig, wire.Bind(new(config.Config), new(*config.ObsConfig)))
